name: toe_tack_tick
description: A simple tic tac toe game ig

version: 9.2.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^4.0.0
  cupertino_icons: ^1.0.2
  go_router: ^7.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  just_audio: ^0.9.34
  flame_audio: ^2.0.4
  animated_text_kit: ^4.2.2
  rive: ^0.11.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/audio/
    - assets/sfx/
  fonts:
    - family: Hello Graduation
      fonts:
        - asset: assets/Hello_Graduation/HelloGraduation.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
